name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        distribution: [ 'zulu', 'temurin', 'corretto' ]
        java: [ '11', '17', '19' ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Java ${{ matrix.java }}-${{ matrix.distribution }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: ${{ matrix.distribution }}
        cache: maven
    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B verify
    - name: Update dependency graph when on master
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      if: ${{ github.ref == 'refs/heads/master' }}
    - name: Get changed files
      uses: tj-actions/verify-changed-files@v14.0.2
      id: verify-changed-files
    - name: Run step only when files change
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      uses: actions/github-script@v6.4.1
      with:
        script: |
            core.setFailed('Changed files found: ${{ steps.verify-changed-files.outputs.changed_files }}')