name: Release to Maven Central
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto
          server-id: ossrh
          server-username: MVN_USERNAME
          server-password: MVN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      - name: Publish package
        run: mvn -ntp -B deploy -P release
        env:
          MVN_USERNAME: ${{ secrets.MVN_USERNAME }}
          MVN_PASSWORD: ${{ secrets.MVN_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

